language: ruby
sudo: false

rvm:
  - 2.0
  - 2.1
  - 2.2

gemfile:
  - gemfiles/activesupport_4.0.gemfile
  - gemfiles/activesupport_4.1.gemfile
  - gemfiles/activesupport_4.2.gemfile
  - gemfiles/activesupport_edge.gemfile

notifications:
  email:
    on_success: change
